#Specify root directory
ROOT = ../../../

#List all c++ files to compile - just one for programs
CFILES = rtcSync.cpp

#List all header files to install
HDRS = rtcSync.h

#List any extra libraries needed
LOCAL_LIBS =

#Set Library name (if one)
LIBRARY = rtcSync.a

#Set Program name - get from CFILE
PROGRAM =

include $(ROOT)/Make/Makefile.rules
