#Specify root directory
ROOT = ../../../

#List all c++ files to compile
CFILES = Packet.cpp Treadport_Types.cpp TRVector.cpp TRQuaternion.cpp Registration_Packet.cpp Registration_Data.cpp Command_Packet.cpp Command_Data.cpp GetUserState_Packet.cpp UserState_Packet.cpp UserState_Data.cpp VirtualState_Packet.cpp VirtualState_Data.cpp Collision_Data.cpp Collision_Packet.cpp NewPos_Data.cpp NewPos_Packet.cpp NewPosResponse_Packet.cpp Stairs_Packet.cpp Stairs_Data.cpp Tracker_Packet.cpp Tracker_Data.cpp FSRSignals_Data.cpp FSRSignals_Packet.cpp ServerRequest_Packet.cpp ServerRequest_Data.cpp ByteArray_Data.cpp ByteArray_Packet.cpp

#List all header files to install
HDRS = Packet.h Packet_Data.h Treadport_Types.h TRVector.h TRQuaternion.h Registration_Packet.h Registration_Data.h Command_Packet.h Command_Data.h GetUserState_Packet.h GetUserState_Data.h UserState_Packet.h UserState_Data.h VirtualState_Packet.h VirtualState_Data.h Collision_Data.h Collision_Packet.h NewPos_Data.h NewPos_Packet.h NewPosResponse_Packet.h NewPosResponse_Data.h Stairs_Packet.h Stairs_Data.h Tracker_Packet.h Tracker_Data.h FSRSignals_Data.h FSRSignals_Packet.h ServerRequest_Packet.h ServerRequest_Data.h ByteArray_Data.h ByteArray_Packet.h

#List any extra libraries needed
LOCAL_LIBS =

#Set Library name (if one)
LIBRARY = libPacket.a

#Set Program name (if one)
#PROGRAM = 

include $(ROOT)/Make/Makefile.rules
 

